spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: organisation
          uri: http://localhost:8002
          predicates:
            - Path=/api/v1/organisation/**
  config:
    import: optional:configserver:http://localhost:8001
server:
  port: 8003

eureka:
  client:
    register-with-eureka: false
